name: cookbook_tests

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  verify:
    strategy:
      matrix:
        cookbooks: ['app_cookbook', 'base_cookbook', 'newapp_cookbook', 'newapp2_cookbook']
    runs-on: ubuntu-latest
    env:
      CHEF_LICENSE: accept-no-persist
    steps:
      - name: Check Out Code
        uses: actions/checkout@v2
      - name: install chef-workstation
        uses: actionshub/chef-install@main
      - name: Cookstyle Check
        run: cd cookbooks/${{ matrix.cookbooks }} && cookbooks/${{ matrix.cookbooks }}
      - name: Unit Test
        run: cd cookbooks/${{ matrix.cookbooks }} && chef exec rspec
      - name: Kitchen Test
        run: cd cookbooks/${{ matrix.cookbooks }} && kitchen test cookbooks
